### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Ajitchy** [substrate-developer-hub/substrate-docs#1225]
This link is broken showing 404
https://docs.substrate.io/rustdocs/latest/pallet_proxy/index.html

**Comment by Ajitchy** [comment]
This link is broken showing 404
https://docs.substrate.io/rustdocs/latest/pallet_proxy/index.html

**Comment by lisa-parity** [comment]
Hi @Ajitchy, 
Yes, we have removed the intermediary rustdocs location, so if you have bookmarks to any Rust docs with rustdocs in the path, the link will not longer work. On the plus side, you'll always be accessing up to date Rust doc instead of a snapshot it it.
https://paritytech.github.io/substrate/master/pallet_proxy/index.html
