### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by melnaquib** [substrate-developer-hub/substrate-docs#1234]
links to rust crates docs are broken
e.g.
https://docs.substrate.io/rustdocs/latest/sp_state_machine/type.StorageValue.html

**Comment by lisa-parity** [comment]
Hi @melnaquib , yes we have removed the intermediary location, so if you have bookmarks to any Rust docs with rustdocs in the path, the link will not longer work. On th eplus side, you'll always be  accessing up to date Rust doc instead of a snapshot it it. 
https://paritytech.github.io/substrate/master/sp_state_machine/type.StorageValue.html
