### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by DieHard073055** [substrate-developer-hub/substrate-docs#1254]
The link on Custom RPCs [RpcExtensionBuilder trait API doc](https://substrate.dev/rustdocs/v3.0.0/sc_service/trait.RpcExtensionBuilder.html).

**Comment by lisa-parity** [comment]
Do you have an older bookmark?
The updated doc here:
https://docs.substrate.io/main-docs/build/custom-rpc/

Uses the updated path:
https://paritytech.github.io/substrate/master/sc_service/trait.RpcExtensionBuilder.html

Any link/bookmark with `rustdocs/v3.0.0` in the path will give you a 404, but the good news is that you will always be directed to a single source of truth instead of a snapshot like was used in the old location.
