### ISSUE TITLE
Bottom Buttons breaking for Tutorials with Hashlinks

### ISSUE THREAD

**Issue by imadarai** [substrate-developer-hub/substrate-docs#147]
e.g. `/v3/kitties/pt1` should point to part2 at the end.  not the next hashlink.

**Comment by imadarai** [comment]
@sacha-l
Just a reminder to let me know how you'd like this to behave.  
You can always use the frontmatter flag to remove the buttons from the pages we don't necessarily need them.  
but in case of Kitties, if we want the next section to be linked, i'll need to quickly revisit the script.

**Comment by imadarai** [comment]
@jimmychu0807 While addressing this I came across a weird problem with Kitties tutorials.  
When I get to the bottom of the tutorial, the button also read `Introduction`.  Which is the title for the next document in progression of Kitties Tutorial.  

I would suggest changing the name in `DevNavMenu` for both Part 1 and Part 2 to perhaps 'Part I - Introduction' & 'Part II - Introduction' ?

**Comment by sacha-l** [comment]
I've addressed this on your #191 branch, just changed the names.

**Comment by jimmychu0807** [comment]
@imadarai I was the one having the PR of changing the devMenu link from just the hash to having the whole page link + hash.

It is because refer to the following scenario. I was at Kitty Tutorial Part I. If I open the Kitty tutorial part II, all the links in Part II section will still point to Part I page + hash. So I figure we need the actual page link, not just the hash.

![Screenshot 2021-10-02 at 07 25 43](https://user-images.githubusercontent.com/898091/135695656-84d8c4cb-107f-4b85-9ad0-b4d8d6a2380a.png)

**Comment by imadarai** [comment]
@jimmychu0807 
I see what you mean.  
I'll review it  today and add a patch or update the links accordingly.  

This does beg a question.  With all the tutorials being a one-page (except kitties), should we perhaps rethink the Tutorial template all together and come up with a better navigation than typicall doc nav?  This is something I can bring up with Marcin and Patrick, but wanted to check with you guys first.  Happy to leave it as is for now, but it might be worth looking into it further down the line.

**Comment by imadarai** [comment]
I've reverted back to previous code and addressed the intended behavior. 

I believe, we'll have a very clear idea of how we'd like to move forward with the next iteration when it comes to navs, or even Tutorial Template as a whole.  This can also use optimization based on #205 during next feature launch.
