### ISSUE TITLE
Input and output are reversed in example for state transitions and storage documentation.

### ISSUE THREAD

**Issue by rlaferla** [substrate-developer-hub/substrate-docs#1555]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Bug report for compiling, code snippets, templates, etc.

In the document, [State transitions and storage](https://docs.substrate.io/fundamentals/state-transitions-and-storage)

The input parameter and output seem to be reversed:

The `"0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"` represents the **Alice** account which when SCALE encoded yields: `"5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"`

Therefore:

`scale_encode("5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY") = "0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"`

should be changed to:

`scale_encode("0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d") = "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"`

### Steps to reproduce the problem

N/A

**Comment by lisa-parity** [comment]
@rlaferla, thanks for submitting this issue.
 The content here does need to be updated, but I don't think the problem is quite what you have here.
5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY is the SS58-encoded public address for the Alice account.
0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d is the address in hex.

The problem in the example (as far as I've been able to ascertain) is that the balance is not stored in the Balances pallet or a FreeBalance storage map in the default implementation. As an optimization for account information, the free balance is in the System pallet. I'll update the examples in this section when revising the content.
