### ISSUE TITLE
Doc of Configure Contract Pallet is out of date

### ISSUE THREAD

**Issue by mngb** [substrate-developer-hub/substrate-docs#1644]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

In https://docs.substrate.io/tutorials/work-with-pallets/contracts-pallet/ 
No such crates named
'pallet-contracts-rpc-runtime-api', 'pallet-contracts-rpc'

### Are you willing to help with this request?

Yes!

**Comment by jjean92** [comment]
What is the solution to go to the end of the tutorial?

**Comment by lisa-parity** [comment]
Potentially more context for this issue:

<img width="1062" alt="error-reported-by-lily" src="https://user-images.githubusercontent.com/92225469/207399869-4cf1e107-8647-4b27-a725-9d222b10fdad.png">

> STEP "Implement the Contracts configuration trait"

**Comment by har00ga** [comment]
Going to fresh install and try and reproduce, didn't have issues a couple weeks ago.

**Comment by jjean92** [comment]
link to pallet_contracts_rpc_runtime_api and pallet_contracts_rpc are broken : 
https://paritytech.github.io/substrate/master/pallet_contracts_rpc_runtime_api/index.html
https://paritytech.github.io/substrate/master/pallet_contracts_rpc/index.html

**Comment by gflow33** [comment]
Any updates regarding this? I have been trying to complete the tutorial but facing similar issues

**Comment by har00ga** [comment]
These crates have been removed (see: https://substrate.stackexchange.com/questions/6375/error-no-matching-package-named-pallet-contracts-rpc-found). Updating the documentation to reflect this.

**Comment by lisa-parity** [comment]
Initially, errors seemed to be caused by a problem in the manifest files.
https://github.com/substrate-developer-hub/substrate-node-template/pull/407
However, after fixing those problems, we discovered major compatibility issues between the pallets required to add the pallets required for smart contracts and the current version of the node template.
To resolve these compatibility issues would require extensive changes to the configuration of the standard node template, including using older versions of all crates and modifying multiple files (far beyond what the tutorial was intended to demonstrate).
  
If you want to experiment with smart contract development for your blockchain, you should use the preconfigured [substrate-contracts-node](https://github.com/paritytech/substrate-contracts-node) instead of the standard node template.
To dive directly into smart contract development, see the tutorials in [Develop smart contracts](/tutorials/smart-contracts/).

If you have trouble with those tutorials, please open a new issue.
