### ISSUE TITLE
Update the tutorial (Upgrade the running network)

### ISSUE THREAD

**Issue by gogosama-dev** [substrate-developer-hub/substrate-docs#1775]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Content request

Hi guys.
I've found out that the last part of this tutorial (where you need to use the Scheduler pallet to schedule a runtime upgrade) simply doesn't work:
https://docs.substrate.io/tutorials/get-started/upgrade-a-running-network/
(if I do everything the tutorial says, I get the "block exhausted" error at all times)

I raised this question on SE (https://substrate.stackexchange.com/questions/6919/update-runtime-sudo-transaction-exhausted-substrate) and people agree that it might be an issue in the tutorial and it needs an update. 

Would love to help, but I haven't been able to figure out how to complete the Scheduler part on my own.
Anyone could help?

### Are you willing to help with this request?

Yes!

**Comment by lisa-parity** [comment]
@gogosama-dev, thanks for posting on StackExchange. I ran into this issue when I updated the first part of the tutorial. I didn't do proper benchmarking for the second part. I was hoping it was a temporary issue in the UI not be in synch. I'll try Oliver's suggestion. If you want to try it as well, you need to add the pallet_utility much like you added the pallet_scheduler to the runtime. After you add the pallet, you should be able to select the pallet in the Polkador/Substrate Portal. I'll try to test this workaround today(and put the benchmarking into my to-do list 😄).

**Comment by lisa-parity** [comment]
@gogosama-dev, it looks like the second part of the tutorial won't work without proper benchmarking. You can use the utility pallet instead of scheduler to do an upgrade with arbitrary weight settings, but that defeats the purpose of the second part of the tutorial.

**Comment by rvalle** [comment]
@lisa-parity the tutorial is still broken then.

I was running it trying to find out what is happening. I understand that the fix is related to an external issue, but how do we do from the POV of the learner?

I mean one will review the exercise a few times, re-try a few times, and start searching to see if others have the same issue before finding this. 

Perhaps it would be possible to link tutorials to opened issued? and generate a troubleshooting section if the issues are still open with a generic: Troubleshooting: the following issues could be affecting this tutorial... or similar.
