### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Wiezzel** [substrate-developer-hub/substrate-docs#1831]
https://docs.substrate.io/build/upgrade-the-runtime/
https://docs.substrate.io/reference/how-to-guides/parachains/runtime-upgrade/

**Comment by lisa-parity** [comment]
@Wiezzel, if you have these bookmarked, here are the new links:
https://docs.substrate.io/maintain/runtime-upgrades/
https://docs.substrate.io/reference/how-to-guides/parachains/upgrade-a-parachain/

**Comment by lisa-parity** [comment]
@Wiezzel, thanks! If you hae topics bookmarked, the new links are:
https://docs.substrate.io/maintain/runtime-upgrades/ (only in Build because I didn't have a Maintain section initially).
https://docs.substrate.io/reference/how-to-guides/parachains/upgrade-a-parachain/ (the same name can't be used twice).

**Comment by Wiezzel** [comment]
@lisa-parity These work fine, thanks. Please update the search to return them as well. Currently, when I type "upgrade" in the "search documentation" box I'm still getting the broken ones.

**Comment by lisa-parity** [comment]
Jonny, updated the indexing.
