### ISSUE TITLE
Improve "Connect to a Relay Chain"

### ISSUE THREAD

**Issue by bkchr** [substrate-developer-hub/substrate-docs#380]
https://docs.substrate.io/how-to-guides/v3/parachains/connect/

Before exporting the genesis state and the genesis wasm we should tell the user to generate a raw chain spec. Then we should tell them to use this raw chain spec for the respective CLI commands to extract the genesis state/wasm.

Users are confused on how to make sure that the chain spec and the registration information are matching.

**Comment by NukeManDan** [comment]
This is covered in https://docs.substrate.io/tutorials/v3/cumulus/start-relay/#create-a-custom-relay-chain-spec-optional -- do you think the content is OK here? We can add a section in the how to guide that foregoes the extra manual customization of the chain spec (as it's not a super common thing to do) and just discusses plain -> raw flow.

**Comment by bkchr** [comment]
I think the linked docs should be updated. In the steps where you generate the gensis-state and genesis-wasm you are not using this chain spec for example.

**Comment by bkchr** [comment]
And this is also about the relay chain chainspec. My issue was about the parachain chainspec.

**Comment by NukeManDan** [comment]
It is possible to download the Wasm and Genesis state registered with a relay in the case you cannot get it otherwise. 

Mention best practice is to always include these files in you got repository alongside the code used to generate it, as we already tell people frequently that non deterministic generation of these files is expected (same code, different hash possibly, but you can use the one submitted on the relay, but better to save it in the canonical repo with your collar code)

 Mention srtool #498

**Comment by bkchr** [comment]
I outlined the process in the issue description. Yes you can download the wasm, but the genesis state will not bring you anything. While this can work, it can also be more complicated. The process I outlined is the easiest one and also not complicated at all.

**Comment by shawntabrizi** [comment]
related pr: https://github.com/substrate-developer-hub/substrate-docs/issues/524

**Comment by lisa-parity** [comment]
This looks to  be pretty out of date.
