### ISSUE TITLE
Update contributor  templates to use `.mdx` prefilled and commented header/section info

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-docs#394]
https://github.com/substrate-developer-hub/substrate-docs/blob/main/static/assets/contribute-templates/how-to-template.md

This is one example, we should have it conform to the style guide and add MD comments to describe things (so they can be left in but render properly for reviewing)

NOTE: github renders .md files _only_ AFAIK.... so it can't be viewed without the rendered branch preview.

**Comment by NukeManDan** [comment]
Is this a duplicate of https://github.com/substrate-developer-hub/substrate-docs/blob/main/v3/docs/00-style-and-contributor-guidelines/d-templates/index.mdx ? I am confused why these exist in two places with two formats :shrug:

**Comment by lsgunnlsgunn** [comment]
Is there any actual value of making them `.mdx` templates? If there's a good reason or a benefit in doing that, it should be fine. It just introduces an unfamiliar element to the audience, I think. Not a huge thing, but a pause.

I'm not imagining contributed content would go directly into documentation without some kind of review/curation to see if the content fits our conventions and to decide where the content should live. I was opting for a frictionless experience for the contributor and the flexibility of named files instead of directories with generic `index.mdx` file names.

But I'm open to other points of view of course!
