### ISSUE TITLE
Polkadot.js app does no longer have developer page in permissioned network tutorial

### ISSUE THREAD

**Issue by fky2015** [substrate-developer-hub/substrate-docs#583]
## Which page you are referring to?
https://docs.substrate.io/tutorials/v3/permissioned-network

## What is the problem?
1. In the [custom type mapping](https://docs.substrate.io/tutorials/v3/permissioned-network/#alice-and-bob-start-the-network) part, it seems that the `PeerId` configuration step can be skipped without affecting the rest of the tutorials.
2. Polkadot.js app is no longer has [developer page](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/settings/developer) in the latest version.

## What could be done?
Delete that part or give a further explanation (why we don't need that now).

**Comment by NukeManDan** [comment]
Good spot! Sorry about the trouble, yes it's awesome: you _don't need custom type definitions manually now_ because of https://github.com/paritytech/substrate/pull/8615 :tada: - I have updated the flow to remove this. New users won't have to worry about this, and those with older versions can now figure out how to. Fixed this in #591
