### ISSUE TITLE
Error content on the page

### ISSUE THREAD

**Issue by gfan8w** [substrate-developer-hub/substrate-docs#611]
### Feedback

The tutorial: https://docs.substrate.io/tutorials/v3/private-network/ 
Do fellowing the steps， when arrive at: 
 [Add keys to the keystore](https://docs.substrate.io/tutorials/v3/private-network/#add-keys-to-the-keystore)
has an error, 

```
./target/release/node-template key insert --base-path /tmp/node01 \
--chain customSpecRaw.json \
--suri <your-secret-key> \
--password-interactive \
--key-type gran
```

when insert the grandpa key, if you use this command, the last result will fail. the blockchain can't finalized.
 the correct command is :

```
./target/release/node-template key insert --base-path /tmp/node01 \
--chain customSpecRaw.json \
--scheme ed25519 \
--suri <your-secret-key> \
--password-interactive \
--key-type gran
```

please refer to:

https://stackoverflow.com/questions/70118810/tutorials-about-start-a-private-substrate-network-where-the-suri-come-from

Further more:
please give more information about how to generate the key and which part of the key to use.
 for example, the content in the tutorial 
```
0x563d22ef5f00e589e07445a3ad88bb92efaa897d7f73a4543d9ac87476434e65
```
is a  private key(Secret seed), but it is randomly copied from somewhere, can't find the context from the tutorial. It gives many confusing to beginner.

**Comment by jimmychu0807** [comment]
Thanks for reporting the issue to us @gfan8w

**Comment by lisa-parity** [comment]
Hi @gfan8w, the missing --scheme option has been fixed (see https://github.com/substrate-developer-hub/substrate-docs/issues/714).

As for the seed used in the tutorial, I understand that it might be confusing. The two options are: use one of the seeds from a well-known account (like alice and bob) or really generate your keys and use those keys instead of copying the keys in the tutorial directly as-is. In a future iteration, I split this tutorial into two separate tutorials--one that simulates a network with alice and bob and one that illustrates generating keys and the chain spec--but this problem of using something from the tutorial as-is still exists. Hopefully, it is a little clearer than the currently published version.

Thanks again for your feedback!
