### ISSUE TITLE
[Tutorial: Start a private network] It is not clear which secret seed to use in the "Add key to keystore" step.

### ISSUE THREAD

**Issue by sanitu** [substrate-developer-hub/substrate-docs#686]
### Content request

The tutorial says: "This example uses the secret seed generated by the key subcommand into the keystore. In this tutorial, the secret seed generated was `0x563d22ef5f00e589e07445a3ad88bb92efaa897d7f73a4543d9ac87476434e65`" but I don't see this secret seed generated in the previous steps.

I think it's less confusing when it says: Use the secret seed that was generated in the **Generate local keys using node template** step. That's the `0x0087016ebbdcf03d1b7b2ad9a958e14a43f2351cd42f2f0a973771b90fb0112f` instead of using a new secret seed and nobody knows where it comes from.

### Are you willing to help with this request?

Yes!

**Comment by sacha-l** [comment]
Thanks for making this issue.

Adding some other points to clarify from a member of the Substrate Devs TG channel:

> The tutorial says, to continue, I can re-use the same keys or I can use another computer to make more keys. What’s unclear to me, is why I would need another machine, and why I can’t use the same machine to generate more keys?

> What I’m hearing in the chat is, I actually can use the same machine to generate more keys. But should I not do this, because the tutorial doesn’t say it’s an option?

**Comment by lisa-parity** [comment]
@sanitu , @sacha-l 
I'm not sure about this because I'm not deeply into the cryptography involved, but I think the issue is not that you can't generate more keys on a single machine, but that unless you change your root identity on a single machine, all of the keys map to a single identity. I guess that the tutorial could have you derive different keys from a single parent, then use those keys but I haven't tested that scenario or figured out if that would make the tutorial more difficult to follow.
